name: gameframework_workspace
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/gameframework
  - packages/gameframework_stream
  - engines/unity/dart
  - engines/unreal/dart
  - example

