name: game_cli
description: CLI tool for Flutter Game Framework to automate Unity and Unreal Engine game exports and integration
version: 0.5.0
homepage: https://github.com/xraph/flutter-game-framework

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  yaml: ^3.1.2
  process_run: ^0.14.0
  cli_util: ^0.4.0
  mason_logger: ^0.2.0
  io: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  game:
